/**
 * Generated by tsnapi — public API snapshot of `exports-md`
 */
// #region Interfaces
export interface GeneratedMarkdown {
  declaration: string;
  fromCache: boolean;
  inputFile: string;
  markdown: string;
}
export interface GenerateMarkdownOptions {
  cwd?: string;
  outDir?: string;
  symbols?: string[];
}
// #endregion

// #region Functions
export declare function findNearestTypescript(_?: string): string;
export declare function generateMarkdownForModule(_: string, _?: GenerateMarkdownOptions): Promise<GeneratedMarkdown>;
// #endregion