/**
 * Generated by tsnapi — public API snapshot of `exports-md`
 */
// #region Interfaces
export interface GeneratedMarkdown {
  declaration: string;
  fromCache: boolean;
  inputFile: string;
  markdown: string;
}
export interface GenerateMarkdownOptions {
  cwd?: string;
  followImports?: boolean;
  followReExports?: boolean;
  github?: GitHubOptions;
  outDir?: string;
  propertyDocs?: PropertyDocMode;
  reverseSymbols?: boolean;
  sortExports?: boolean;
  sortSymbols?: boolean;
  symbols?: string[];
}
export interface GitHubOptions {
  repository?: string;
  searchLinks?: boolean;
}
// #endregion

// #region Types
export type PropertyDocMode = 'inline' | 'list';
// #endregion

// #region Functions
export declare function findNearestTypescript(_?: string): string;
export declare function generateMarkdownForModule(_: string, _?: GenerateMarkdownOptions): Promise<GeneratedMarkdown>;
// #endregion